from typing import Protocol

class LoggerInterface(Protocol):
    """
    Enterprise-grade logger interface for dependency inversion and testability.
    Any logger implementation (standard logging, custom, or mock) should implement these methods.
    """
    def info(self, msg: str, *args, **kwargs): ...
    def warning(self, msg: str, *args, **kwargs): ...
    def error(self, msg: str, *args, **kwargs): ...
    def debug(self, msg: str, *args, **kwargs): ...